float getFloat(char mensaje[]);
int getInt(char mensaje[]);
int getIntPositivo(char mensaje[], char eMensaje[]);
int getIntLimitado(char mensaje[], char eMensaje[], int lowLimit, int highLimit);
char getChar(char mensaje[]);
char getNumeroAleatorio(int desde , int hasta, int iniciar);
int esNumerico(char str[]);
int esSoloLetras(char str[]);
int esAlfaNumerico(char str[]);
int esTelefono(char str[]);
void getString(char mensaje[],char input[]);
int getStringLetras(char mensaje[],char input[]);
int getStringNumeros(char mensaje[],char input[]);
char getCharSexo(void);
int lengthString(char str[],int length);
